version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "Wait for 10 seconds"
          command: "sleep 10"
      - run:
          name: "Install dependencies"
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
      - run:
          name: "Run a series of commands"
          command: |
            for i in {1..10}
            do
              echo "Iteration $i"
              sleep 5
            done
      - run:
          name: "Download a large file"
          command: "curl -O https://speed.hetzner.de/100MB.bin"
      - run:
          name: "Wait for another 10 seconds"
          command: "sleep 10"
      - run:
          name: "Remove the large file"
          command: "rm 100MB.bin"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
