# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: echo "Hello, World!"

  manual-build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Manual build"
          command: echo "This is a manually triggered build!"

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
      - hold:
          type: approval
          requires:
            - say-hello
      - manual-build:
          requires:
            - hold