version: 2
jobs:
  say-hello:
    docker:
    - image: cimg/base:current
    steps:
    - checkout
    - run:
        name: Say hello
        command: echo Hello, World!
workflows:
  say-hello-workflow:
    jobs:
    - say-hello
  version: 2
